site:
    pretty_urls: true
    templates_dirs: macros
    title: B0LT80
    sources:
        pages:
            data_endpoint: site.pages
            item_name: page
    routes:
        -
          func: pcurl(slug)
          page_suffix: /%num%
          source: pages
          url: /%path:slug%

baker:
    ignore:
        - bootstrap
        - pure
        - stupidhttp

jinja:
    twig_compatibility: true

markdown:
    use_markdown_extra: true

smartypants:
    enable: true
    use_smartypants_typographer: true

