site:
    title: B O L T 8 0
    pretty_urls: true
    templates_dirs: ../../_shared/templates
    plugins_dirs: ../plugins

markdown:
    use_markdown_extra: true

smartypants:
    enable: true
    use_smartypants_typographer: true

baker:
    skip_patterns:
        - /^_/
        - index.php
        - .htaccess
        - web.config
    config_variants:
        default:
            site:
                root: http://bolt80.com
        local:
            baker:
                file_urls: true
            site:
                pretty_urls: false
