site:
    title: B O L T 8 0
    pretty_urls: true
    template_dirs: ../../_shared/templates

markdown:
    use_markdown_extra: true

smartypants:
    enable: true
    use_smartypants_typographer: true

baker:
    skip_patterns:
        - /^_/
        - index.php
        - .htaccess
        - web.config
